// Comprehensive global medicine database

export interface MedicineEntry {
  name: string;
  aliases: string[];
  category: string;
  description: string;
  uses: string;
  dosage: string;
  sideEffects: string;
  warnings: string;
  icon: string;
}

export interface SymptomEntry {
  symptom: string;
  aliases: string[];
  description: string;
  possibleCauses: string[];
  advice: string;
  whenToSeeDoctor: string;
  remedies: string[];
  icon: string;
}

export const MEDICINE_DB: MedicineEntry[] = [
  // --- Pain & Fever ---
  { name: 'Paracetamol (Acetaminophen)', aliases: ['paracetamol','acetaminophen','tylenol','calpol','panadol'], category: 'Pain & Fever', description: 'One of the most widely used pain relievers and fever reducers worldwide.', uses: 'Headache, toothache, body aches, fever, cold & flu symptoms, mild arthritis.', dosage: 'Adults: 500–1000 mg every 4–6 hours. Max 4 g/day. Children: weight-based dosing.', sideEffects: 'Rare at normal doses. Overdose can cause severe liver damage.', warnings: 'Avoid alcohol. Do not exceed max dose. Caution with liver disease.', icon: '💊' },
  { name: 'Ibuprofen', aliases: ['ibuprofen','advil','motrin','brufen','nurofen'], category: 'Pain & Inflammation', description: 'Nonsteroidal anti-inflammatory drug (NSAID) for pain, inflammation, and fever.', uses: 'Headache, dental pain, menstrual cramps, muscle pain, arthritis, fever.', dosage: 'Adults: 200–400 mg every 4–6 hours. Max 1200 mg/day (OTC). Take with food.', sideEffects: 'Stomach upset, nausea, dizziness, headache. Rarely: GI bleeding.', warnings: 'Avoid if pregnant (3rd trimester), kidney disease, or stomach ulcers. Take with food.', icon: '🔥' },
  { name: 'Aspirin', aliases: ['aspirin','ecosprin','disprin','bayer'], category: 'Pain & Blood Thinner', description: 'NSAID used for pain, fever, inflammation, and heart attack/stroke prevention.', uses: 'Pain, fever, inflammation, prevention of blood clots, heart attacks, strokes.', dosage: 'Pain: 325–650 mg every 4–6 hours. Heart: 75–100 mg daily. Take with food.', sideEffects: 'Stomach upset, bleeding, tinnitus at high doses.', warnings: 'Not for children under 16 (Reye syndrome risk). Avoid with blood thinners.', icon: '💉' },
  { name: 'Naproxen', aliases: ['naproxen','aleve','naprosyn','anaprox'], category: 'Pain & Inflammation', description: 'Long-acting NSAID for pain and inflammation.', uses: 'Arthritis, gout, menstrual cramps, tendinitis, headache, muscle pain.', dosage: 'Adults: 250–500 mg twice daily. Max 1250 mg/day. Take with food.', sideEffects: 'Stomach upset, drowsiness, headache, dizziness.', warnings: 'Avoid with kidney disease, heart failure, or stomach ulcers.', icon: '💪' },
  { name: 'Diclofenac', aliases: ['diclofenac','voltaren','cataflam','voltarol'], category: 'Pain & Inflammation', description: 'Potent NSAID available as tablets, gels, and injections.', uses: 'Arthritis, back pain, sports injuries, gout, post-surgical pain.', dosage: 'Adults: 50 mg 2–3 times daily. Gel: apply 3–4 times daily. Take tablets with food.', sideEffects: 'Stomach upset, headache, dizziness. Gel: skin irritation.', warnings: 'Increased cardiovascular risk with long-term use. Avoid in heart disease.', icon: '🩹' },
  { name: 'Tramadol', aliases: ['tramadol','ultram','tramal'], category: 'Pain (Opioid)', description: 'Moderate-strength opioid pain reliever for moderate to severe pain.', uses: 'Moderate to severe pain, post-surgical pain, chronic pain.', dosage: 'Adults: 50–100 mg every 4–6 hours. Max 400 mg/day. Prescription only.', sideEffects: 'Nausea, dizziness, constipation, drowsiness, headache.', warnings: '⚠️ Prescription only. Risk of dependence. Do not mix with alcohol or sedatives.', icon: '⚠️' },

  // --- Antibiotics ---
  { name: 'Amoxicillin', aliases: ['amoxicillin','amoxil','augmentin','moxatag'], category: 'Antibiotic', description: 'Broad-spectrum penicillin antibiotic for bacterial infections.', uses: 'Ear infections, sinusitis, pneumonia, urinary tract infections, dental infections.', dosage: 'Adults: 250–500 mg every 8 hours or 500–875 mg every 12 hours. Complete full course.', sideEffects: 'Diarrhea, nausea, rash. Rarely: allergic reactions.', warnings: 'Complete the full course. Inform doctor of penicillin allergy. May reduce oral contraceptive effectiveness.', icon: '🦠' },
  { name: 'Azithromycin', aliases: ['azithromycin','zithromax','azithral','zpack'], category: 'Antibiotic', description: 'Macrolide antibiotic effective against many bacterial infections.', uses: 'Respiratory infections, ear infections, skin infections, STIs, traveler\'s diarrhea.', dosage: 'Usually 500 mg day 1, then 250 mg days 2–5. Or 500 mg daily for 3 days.', sideEffects: 'Nausea, diarrhea, stomach pain, headache.', warnings: 'May cause irregular heartbeat. Avoid with certain heart conditions.', icon: '🔬' },
  { name: 'Ciprofloxacin', aliases: ['ciprofloxacin','cipro','ciplox'], category: 'Antibiotic', description: 'Fluoroquinolone antibiotic for serious bacterial infections.', uses: 'UTIs, respiratory infections, bone infections, anthrax, certain GI infections.', dosage: 'Adults: 250–750 mg every 12 hours. Duration varies by infection.', sideEffects: 'Nausea, diarrhea, dizziness, tendon problems.', warnings: '⚠️ Risk of tendon rupture. Avoid in children. Avoid dairy products near dosing.', icon: '🧫' },
  { name: 'Metronidazole', aliases: ['metronidazole','flagyl','metrogyl'], category: 'Antibiotic/Antiparasitic', description: 'Antibiotic effective against anaerobic bacteria and parasites.', uses: 'Dental infections, bacterial vaginosis, C. diff, H. pylori, amoebic infections.', dosage: 'Adults: 400–500 mg 2–3 times daily for 5–10 days.', sideEffects: 'Nausea, metallic taste, darkened urine, headache.', warnings: '🚫 Absolutely NO alcohol during treatment and 48 hours after. Causes severe reaction.', icon: '🦷' },
  { name: 'Doxycycline', aliases: ['doxycycline','vibramycin','doryx'], category: 'Antibiotic', description: 'Tetracycline antibiotic with broad antimicrobial activity.', uses: 'Acne, respiratory infections, Lyme disease, malaria prevention, STIs.', dosage: 'Adults: 100 mg once or twice daily. Take with plenty of water.', sideEffects: 'Sun sensitivity, nausea, esophageal irritation.', warnings: 'Avoid sun exposure. Do not take with dairy. Not for pregnant women or children under 8.', icon: '☀️' },
  { name: 'Cephalexin', aliases: ['cephalexin','keflex','cefalexin'], category: 'Antibiotic', description: 'First-generation cephalosporin antibiotic.', uses: 'Skin infections, UTIs, respiratory infections, bone infections, ear infections.', dosage: 'Adults: 250–500 mg every 6 hours. Complete full course.', sideEffects: 'Diarrhea, nausea, stomach pain, headache.', warnings: 'Inform doctor of penicillin allergy (cross-reactivity possible).', icon: '💊' },

  // --- Heart & Blood Pressure ---
  { name: 'Amlodipine', aliases: ['amlodipine','norvasc','amlopress'], category: 'Blood Pressure', description: 'Calcium channel blocker for high blood pressure and angina.', uses: 'Hypertension (high blood pressure), coronary artery disease, angina.', dosage: 'Adults: 5–10 mg once daily. May take 1–2 weeks for full effect.', sideEffects: 'Ankle swelling, flushing, headache, dizziness, fatigue.', warnings: 'Do not stop suddenly. Avoid grapefruit juice. Monitor blood pressure regularly.', icon: '❤️' },
  { name: 'Atenolol', aliases: ['atenolol','tenormin'], category: 'Blood Pressure', description: 'Beta-blocker that slows heart rate and lowers blood pressure.', uses: 'Hypertension, angina, irregular heartbeat, heart attack prevention.', dosage: 'Adults: 25–100 mg once daily.', sideEffects: 'Tiredness, cold hands/feet, slow heartbeat, dizziness.', warnings: 'Do not stop suddenly (can worsen heart condition). Caution in diabetes and asthma.', icon: '💓' },
  { name: 'Lisinopril', aliases: ['lisinopril','zestril','prinivil'], category: 'Blood Pressure', description: 'ACE inhibitor for blood pressure and heart failure.', uses: 'Hypertension, heart failure, post-heart attack, diabetic kidney protection.', dosage: 'Adults: 5–40 mg once daily.', sideEffects: 'Dry cough, dizziness, headache, fatigue, high potassium.', warnings: 'Not for pregnant women. Monitor kidney function. Avoid potassium supplements.', icon: '🫀' },
  { name: 'Losartan', aliases: ['losartan','cozaar'], category: 'Blood Pressure', description: 'Angiotensin receptor blocker (ARB) for hypertension.', uses: 'Hypertension, diabetic nephropathy, heart failure, stroke prevention.', dosage: 'Adults: 50–100 mg once daily.', sideEffects: 'Dizziness, fatigue, nasal congestion, back pain.', warnings: 'Not for pregnant women. Monitor potassium and kidney function.', icon: '🩸' },
  { name: 'Hydrochlorothiazide', aliases: ['hydrochlorothiazide','hctz','microzide'], category: 'Diuretic', description: 'Thiazide diuretic (water pill) for blood pressure and fluid retention.', uses: 'Hypertension, edema, heart failure, kidney stones prevention.', dosage: 'Adults: 12.5–50 mg once daily. Take in the morning.', sideEffects: 'Frequent urination, dizziness, low potassium, sun sensitivity.', warnings: 'Stay hydrated. Monitor electrolytes. May increase blood sugar.', icon: '💧' },
  { name: 'Warfarin', aliases: ['warfarin','coumadin','jantoven'], category: 'Blood Thinner', description: 'Anticoagulant (blood thinner) to prevent blood clots.', uses: 'DVT, pulmonary embolism, atrial fibrillation, mechanical heart valves.', dosage: 'Dose varies by INR levels. Regular blood tests required. Take at same time daily.', sideEffects: 'Bleeding, bruising, hair loss. Rarely: skin necrosis.', warnings: '⚠️ Many drug & food interactions (especially vitamin K). Regular INR monitoring required.', icon: '🩸' },
  { name: 'Clopidogrel', aliases: ['clopidogrel','plavix'], category: 'Blood Thinner', description: 'Antiplatelet drug to prevent blood clots.', uses: 'Heart attack prevention, stroke prevention, peripheral artery disease, stent placement.', dosage: 'Adults: 75 mg once daily. Loading dose: 300 mg if needed.', sideEffects: 'Bleeding, bruising, diarrhea, stomach pain.', warnings: 'Avoid with omeprazole (reduces effectiveness). Inform surgeons before procedures.', icon: '🫀' },

  // --- Diabetes ---
  { name: 'Metformin', aliases: ['metformin','glucophage','glycomet','fortamet'], category: 'Diabetes', description: 'First-line medication for type 2 diabetes.', uses: 'Type 2 diabetes, PCOS, prediabetes, insulin resistance.', dosage: 'Adults: Start 500 mg 1–2 times daily with meals. Max 2550 mg/day.', sideEffects: 'Nausea, diarrhea, stomach pain, metallic taste. Usually improve with time.', warnings: 'Stop before contrast dye procedures. Avoid excessive alcohol. Rare: lactic acidosis.', icon: '🍬' },
  { name: 'Glimepiride', aliases: ['glimepiride','amaryl'], category: 'Diabetes', description: 'Sulfonylurea that stimulates insulin release from the pancreas.', uses: 'Type 2 diabetes (when metformin alone is insufficient).', dosage: 'Adults: 1–4 mg once daily with breakfast. Max 8 mg/day.', sideEffects: 'Low blood sugar (hypoglycemia), weight gain, dizziness, nausea.', warnings: '⚠️ Risk of hypoglycemia. Eat regular meals. Carry glucose tablets.', icon: '💉' },
  { name: 'Insulin (all types)', aliases: ['insulin','lantus','novorapid','humalog','novolog','levemir','tresiba'], category: 'Diabetes', description: 'Hormone used to manage blood sugar in diabetes.', uses: 'Type 1 diabetes (essential), type 2 diabetes (when oral meds insufficient).', dosage: 'Highly individualized. Adjust based on blood sugar, meals, and activity.', sideEffects: 'Low blood sugar, weight gain, injection site reactions.', warnings: '⚠️ Monitor blood sugar regularly. Rotate injection sites. Store properly (refrigerate).', icon: '💉' },
  { name: 'Sitagliptin', aliases: ['sitagliptin','januvia'], category: 'Diabetes', description: 'DPP-4 inhibitor that helps regulate blood sugar.', uses: 'Type 2 diabetes (often combined with metformin).', dosage: 'Adults: 100 mg once daily.', sideEffects: 'Headache, stuffy nose, sore throat, upper respiratory infection.', warnings: 'Adjust dose for kidney impairment. Rare: pancreatitis.', icon: '🍬' },

  // --- Cholesterol ---
  { name: 'Atorvastatin', aliases: ['atorvastatin','lipitor','atorva'], category: 'Cholesterol', description: 'Statin that lowers LDL cholesterol and triglycerides.', uses: 'High cholesterol, heart disease prevention, stroke prevention.', dosage: 'Adults: 10–80 mg once daily, usually at bedtime.', sideEffects: 'Muscle pain, headache, nausea, liver enzyme elevation.', warnings: 'Report unexplained muscle pain immediately. Avoid grapefruit. Regular liver function tests.', icon: '📉' },
  { name: 'Rosuvastatin', aliases: ['rosuvastatin','crestor','rosuvas'], category: 'Cholesterol', description: 'Potent statin for cholesterol management.', uses: 'High cholesterol, cardiovascular disease prevention.', dosage: 'Adults: 5–40 mg once daily.', sideEffects: 'Muscle pain, headache, nausea, weakness.', warnings: 'Same as atorvastatin. Report muscle symptoms promptly.', icon: '📉' },

  // --- Stomach & Digestion ---
  { name: 'Omeprazole', aliases: ['omeprazole','prilosec','losec','omez'], category: 'Stomach Acid', description: 'Proton pump inhibitor (PPI) that reduces stomach acid.', uses: 'GERD, stomach ulcers, H. pylori (with antibiotics), Zollinger-Ellison.', dosage: 'Adults: 20–40 mg once daily, 30 min before meals. Usually 4–8 weeks.', sideEffects: 'Headache, nausea, diarrhea, stomach pain, flatulence.', warnings: 'Long-term use may affect calcium/magnesium absorption and bone density.', icon: '🧪' },
  { name: 'Pantoprazole', aliases: ['pantoprazole','protonix','pantop'], category: 'Stomach Acid', description: 'PPI for acid-related stomach conditions.', uses: 'GERD, erosive esophagitis, stomach ulcers, Zollinger-Ellison.', dosage: 'Adults: 20–40 mg once daily before breakfast.', sideEffects: 'Headache, diarrhea, nausea, abdominal pain.', warnings: 'Same long-term concerns as omeprazole.', icon: '🧪' },
  { name: 'Ranitidine', aliases: ['ranitidine','zantac'], category: 'Stomach Acid', description: 'H2 blocker that reduces stomach acid (largely withdrawn, famotidine is alternative).', uses: 'Was used for GERD, ulcers, heartburn. Now replaced by famotidine.', dosage: 'Adults: 150 mg twice daily or 300 mg at bedtime (if available).', sideEffects: 'Headache, dizziness, constipation, diarrhea.', warnings: '⚠️ Largely withdrawn worldwide due to NDMA contamination concerns. Use famotidine instead.', icon: '⚠️' },
  { name: 'Domperidone', aliases: ['domperidone','motilium'], category: 'Nausea/Vomiting', description: 'Anti-nausea medication that promotes stomach emptying.', uses: 'Nausea, vomiting, bloating, gastroparesis, reflux.', dosage: 'Adults: 10 mg up to 3 times daily before meals. Max 30 mg/day.', sideEffects: 'Dry mouth, headache, drowsiness. Rarely: irregular heartbeat.', warnings: 'Avoid with certain heart conditions. Short-term use preferred.', icon: '🤢' },
  { name: 'Ondansetron', aliases: ['ondansetron','zofran'], category: 'Nausea/Vomiting', description: 'Powerful anti-nausea medication commonly used during chemotherapy.', uses: 'Nausea/vomiting from chemotherapy, surgery, radiation, gastroenteritis.', dosage: 'Adults: 4–8 mg every 8 hours as needed.', sideEffects: 'Headache, constipation, fatigue, dizziness.', warnings: 'May cause QT prolongation. Avoid with other QT-prolonging drugs.', icon: '🤢' },
  { name: 'Loperamide', aliases: ['loperamide','imodium'], category: 'Diarrhea', description: 'Anti-diarrheal that slows intestinal movement.', uses: 'Acute diarrhea, chronic diarrhea, traveler\'s diarrhea.', dosage: 'Adults: 4 mg initially, then 2 mg after each loose stool. Max 16 mg/day.', sideEffects: 'Constipation, nausea, dizziness, abdominal cramps.', warnings: 'Do not use if bloody diarrhea or fever. Do not exceed recommended dose.', icon: '🚽' },

  // --- Respiratory ---
  { name: 'Salbutamol (Albuterol)', aliases: ['salbutamol','albuterol','ventolin','proventil','asthalin'], category: 'Asthma/COPD', description: 'Bronchodilator inhaler for quick relief of asthma symptoms.', uses: 'Asthma attacks, COPD, exercise-induced bronchospasm, wheezing.', dosage: 'Inhaler: 1–2 puffs every 4–6 hours as needed. Nebulizer: 2.5 mg.', sideEffects: 'Tremor, fast heartbeat, headache, nervousness.', warnings: 'If using more than 2 times/week, asthma may not be well controlled. See doctor.', icon: '🌬️' },
  { name: 'Montelukast', aliases: ['montelukast','singulair'], category: 'Asthma/Allergies', description: 'Leukotriene receptor antagonist for asthma and allergies.', uses: 'Asthma prevention, allergic rhinitis, exercise-induced bronchospasm.', dosage: 'Adults: 10 mg once daily in the evening.', sideEffects: 'Headache, stomach pain, fatigue. Rarely: mood changes.', warnings: '⚠️ FDA warning about neuropsychiatric events (mood changes, suicidal thoughts).', icon: '🫁' },
  { name: 'Fluticasone', aliases: ['fluticasone','flonase','flovent','flixotide'], category: 'Corticosteroid', description: 'Inhaled/nasal corticosteroid for asthma and allergies.', uses: 'Asthma maintenance, allergic rhinitis, nasal congestion.', dosage: 'Inhaler: 100–500 mcg twice daily. Nasal spray: 1–2 sprays per nostril daily.', sideEffects: 'Oral thrush (inhaler), nosebleeds (nasal), hoarseness.', warnings: 'Rinse mouth after inhaler use. Not for acute attacks.', icon: '👃' },

  // --- Allergies ---
  { name: 'Cetirizine', aliases: ['cetirizine','zyrtec','alerid'], category: 'Antihistamine', description: 'Second-generation antihistamine for allergies.', uses: 'Hay fever, hives, allergic rhinitis, itchy eyes, insect bites.', dosage: 'Adults: 10 mg once daily. Can cause mild drowsiness.', sideEffects: 'Drowsiness, dry mouth, headache, fatigue.', warnings: 'May cause drowsiness. Use caution when driving.', icon: '🤧' },
  { name: 'Loratadine', aliases: ['loratadine','claritin','alavert'], category: 'Antihistamine', description: 'Non-drowsy antihistamine for allergy relief.', uses: 'Hay fever, hives, allergic rhinitis, itching.', dosage: 'Adults: 10 mg once daily.', sideEffects: 'Headache, dry mouth, fatigue (less drowsy than cetirizine).', warnings: 'Generally well tolerated. Adjust dose for liver/kidney issues.', icon: '🌸' },
  { name: 'Fexofenadine', aliases: ['fexofenadine','allegra','telfast'], category: 'Antihistamine', description: 'Non-sedating antihistamine for allergy symptoms.', uses: 'Seasonal allergies, chronic hives, allergic rhinitis.', dosage: 'Adults: 120–180 mg once daily.', sideEffects: 'Headache, back pain, nausea (minimal drowsiness).', warnings: 'Avoid fruit juices within 1–2 hours (reduces absorption).', icon: '🌼' },
  { name: 'Diphenhydramine', aliases: ['diphenhydramine','benadryl'], category: 'Antihistamine (Sedating)', description: 'First-generation antihistamine that also helps with sleep.', uses: 'Allergic reactions, insomnia, motion sickness, itching, cold symptoms.', dosage: 'Adults: 25–50 mg every 4–6 hours. Max 300 mg/day.', sideEffects: 'Drowsiness, dry mouth, blurred vision, urinary retention.', warnings: '⚠️ Very sedating. Do not drive. Avoid in elderly (confusion risk).', icon: '😴' },

  // --- Mental Health ---
  { name: 'Sertraline', aliases: ['sertraline','zoloft','lustral'], category: 'Antidepressant (SSRI)', description: 'Selective serotonin reuptake inhibitor for depression and anxiety.', uses: 'Depression, anxiety, PTSD, OCD, panic disorder, social anxiety.', dosage: 'Adults: 50–200 mg once daily. Start low, increase gradually.', sideEffects: 'Nausea, diarrhea, insomnia, sexual dysfunction, headache.', warnings: '⚠️ Do not stop suddenly (withdrawal). Takes 4–6 weeks for full effect. Monitor for suicidal thoughts initially.', icon: '🧠' },
  { name: 'Fluoxetine', aliases: ['fluoxetine','prozac','sarafem'], category: 'Antidepressant (SSRI)', description: 'Popular SSRI antidepressant with long half-life.', uses: 'Depression, OCD, bulimia, panic disorder, PMDD.', dosage: 'Adults: 20–80 mg once daily in the morning.', sideEffects: 'Nausea, insomnia, anxiety, headache, sexual dysfunction.', warnings: 'Same as sertraline. Long half-life means effects persist after stopping.', icon: '🧠' },
  { name: 'Escitalopram', aliases: ['escitalopram','lexapro','cipralex'], category: 'Antidepressant (SSRI)', description: 'Refined SSRI with fewer side effects than older antidepressants.', uses: 'Depression, generalized anxiety disorder.', dosage: 'Adults: 10–20 mg once daily.', sideEffects: 'Nausea, headache, insomnia, sexual dysfunction, drowsiness.', warnings: 'Do not stop suddenly. Takes 2–4 weeks to feel improvement.', icon: '🧠' },
  { name: 'Alprazolam', aliases: ['alprazolam','xanax'], category: 'Anti-Anxiety (Benzodiazepine)', description: 'Fast-acting benzodiazepine for anxiety and panic disorders.', uses: 'Anxiety disorders, panic attacks, insomnia (short-term).', dosage: 'Adults: 0.25–0.5 mg 3 times daily. Use lowest effective dose.', sideEffects: 'Drowsiness, fatigue, memory problems, dizziness.', warnings: '⚠️ Prescription only. High addiction risk. Do not mix with alcohol. Do not stop suddenly.', icon: '⚠️' },
  { name: 'Diazepam', aliases: ['diazepam','valium'], category: 'Anti-Anxiety (Benzodiazepine)', description: 'Long-acting benzodiazepine for anxiety, seizures, and muscle spasms.', uses: 'Anxiety, muscle spasms, seizures, alcohol withdrawal, sedation.', dosage: 'Adults: 2–10 mg 2–4 times daily. Highly individualized.', sideEffects: 'Drowsiness, fatigue, muscle weakness, confusion.', warnings: '⚠️ High addiction potential. Do not mix with alcohol or opioids. Taper slowly to stop.', icon: '⚠️' },

  // --- Thyroid ---
  { name: 'Levothyroxine', aliases: ['levothyroxine','synthroid','eltroxin','thyronorm','euthyrox'], category: 'Thyroid', description: 'Synthetic thyroid hormone for hypothyroidism.', uses: 'Hypothyroidism, thyroid cancer (post-surgery), goiter.', dosage: 'Adults: 25–200 mcg once daily on empty stomach, 30–60 min before breakfast.', sideEffects: 'Usually none at correct dose. Overdose: palpitations, weight loss, tremor.', warnings: 'Take on empty stomach. Wait 4 hours before calcium/iron. Regular thyroid level tests.', icon: '🦋' },

  // --- Vitamins & Supplements ---
  { name: 'Vitamin D3', aliases: ['vitamin d3','vitamin d','cholecalciferol','d3'], category: 'Vitamin', description: 'Essential vitamin for bone health, immune function, and mood.', uses: 'Vitamin D deficiency, bone health, immune support, mood regulation.', dosage: 'Adults: 600–2000 IU daily. Higher doses for deficiency (prescribed).', sideEffects: 'Rare at normal doses. Excess: nausea, weakness, kidney problems.', warnings: 'Best absorbed with fatty foods. Get levels checked before high doses.', icon: '☀️' },
  { name: 'Vitamin B12', aliases: ['vitamin b12','b12','cyanocobalamin','methylcobalamin'], category: 'Vitamin', description: 'Essential for nerve function, red blood cells, and DNA synthesis.', uses: 'B12 deficiency, pernicious anemia, nerve damage, fatigue, vegetarian supplementation.', dosage: 'Oral: 1000–2000 mcg daily. Injection: 1000 mcg monthly (severe deficiency).', sideEffects: 'Very rare. Mild diarrhea, itching at injection site.', warnings: 'Vegetarians/vegans at risk of deficiency. Elderly may need injections (poor absorption).', icon: '🔴' },
  { name: 'Iron (Ferrous Sulfate)', aliases: ['iron','ferrous sulfate','ferrous fumarate','fer-in-sol'], category: 'Mineral', description: 'Essential mineral for red blood cell production.', uses: 'Iron deficiency anemia, pregnancy supplementation, fatigue from low iron.', dosage: 'Adults: 325 mg (65 mg elemental iron) 1–3 times daily. Take with vitamin C.', sideEffects: 'Constipation, nausea, black stools, stomach upset.', warnings: 'Take on empty stomach if tolerated. Separate from calcium, antacids, and tea by 2 hours.', icon: '🩸' },
  { name: 'Calcium', aliases: ['calcium','calcium carbonate','calcium citrate','caltrate','os-cal'], category: 'Mineral', description: 'Essential mineral for bone health and muscle function.', uses: 'Osteoporosis prevention, calcium deficiency, muscle cramps.', dosage: 'Adults: 500–600 mg per dose, up to 1000–1200 mg/day. Take with food (carbonate).', sideEffects: 'Constipation, bloating, gas.', warnings: 'Separate from iron and thyroid medications by 4 hours. Don\'t exceed 2500 mg/day.', icon: '🦴' },
  { name: 'Folic Acid', aliases: ['folic acid','folate','vitamin b9'], category: 'Vitamin', description: 'B vitamin essential for cell growth and pregnancy health.', uses: 'Pregnancy (prevents birth defects), anemia, folate deficiency.', dosage: 'Adults: 400 mcg daily. Pregnancy: 400–800 mcg daily.', sideEffects: 'Generally very safe. Rare: nausea, bloating.', warnings: 'Essential before and during early pregnancy. May mask B12 deficiency.', icon: '🤰' },
  { name: 'Omega-3 Fish Oil', aliases: ['omega 3','fish oil','omega-3','epa','dha'], category: 'Supplement', description: 'Essential fatty acids for heart and brain health.', uses: 'Heart health, high triglycerides, joint inflammation, brain function, dry eyes.', dosage: 'Adults: 1000–4000 mg daily (250–500 mg combined EPA+DHA minimum).', sideEffects: 'Fishy aftertaste, burping, mild GI upset.', warnings: 'High doses may increase bleeding risk. Inform doctor if on blood thinners.', icon: '🐟' },
  { name: 'Multivitamin', aliases: ['multivitamin','centrum','one a day'], category: 'Supplement', description: 'Combination of essential vitamins and minerals.', uses: 'Nutritional supplementation, fill dietary gaps, general wellness.', dosage: 'Adults: 1 tablet daily with food.', sideEffects: 'Nausea (if taken on empty stomach), constipation (iron content).', warnings: 'Not a substitute for balanced diet. Avoid taking multiple supplements that overlap.', icon: '🌈' },

  // --- Sleep ---
  { name: 'Melatonin', aliases: ['melatonin'], category: 'Sleep Aid', description: 'Natural hormone supplement that regulates sleep-wake cycle.', uses: 'Insomnia, jet lag, shift work sleep disorder, sleep onset difficulty.', dosage: 'Adults: 0.5–5 mg 30–60 minutes before bedtime. Start with lowest dose.', sideEffects: 'Drowsiness, headache, dizziness, nausea.', warnings: 'May interact with blood thinners and diabetes medications. Not for long-term use without doctor advice.', icon: '🌙' },
  { name: 'Zolpidem', aliases: ['zolpidem','ambien','stilnox'], category: 'Sleep Aid', description: 'Prescription sleep medication for short-term insomnia treatment.', uses: 'Short-term treatment of insomnia (difficulty falling asleep).', dosage: 'Adults: 5–10 mg immediately before bedtime. Women: start at 5 mg.', sideEffects: 'Drowsiness, dizziness, diarrhea. Rarely: sleepwalking, memory gaps.', warnings: '⚠️ Prescription only. Risk of dependence. Do not mix with alcohol. Allow 7–8 hours for sleep.', icon: '😴' },

  // --- Skin ---
  { name: 'Hydrocortisone Cream', aliases: ['hydrocortisone','cortisone cream'], category: 'Topical Steroid', description: 'Mild corticosteroid cream for skin inflammation and itching.', uses: 'Eczema, dermatitis, insect bites, rashes, mild allergic skin reactions.', dosage: 'Apply thin layer 1–2 times daily. Do not use for more than 7 days without doctor advice.', sideEffects: 'Skin thinning (prolonged use), burning/stinging at application site.', warnings: 'Do not use on face for long periods. Not for fungal or bacterial infections.', icon: '🧴' },
  { name: 'Clotrimazole', aliases: ['clotrimazole','canesten','lotrimin'], category: 'Antifungal', description: 'Topical antifungal for fungal skin infections.', uses: 'Athlete\'s foot, ringworm, jock itch, yeast infections, fungal nappy rash.', dosage: 'Apply 2–3 times daily for 2–4 weeks. Continue 2 weeks after symptoms clear.', sideEffects: 'Mild burning, irritation, or redness at application site.', warnings: 'Complete full course even if symptoms improve early.', icon: '🍄' },

  // --- Eye ---
  { name: 'Artificial Tears', aliases: ['artificial tears','eye drops','refresh tears','systane'], category: 'Eye Care', description: 'Lubricant eye drops for dry, irritated eyes.', uses: 'Dry eyes, eye strain, contact lens discomfort, environmental irritation.', dosage: 'Apply 1–2 drops as needed throughout the day.', sideEffects: 'Temporary blurring, mild stinging.', warnings: 'Discard 28 days after opening (preservative-free). Do not touch dropper tip to eye.', icon: '👁️' },

  // --- Miscellaneous ---
  { name: 'Prednisone', aliases: ['prednisone','prednisolone','deltasone','omnacortil'], category: 'Corticosteroid', description: 'Powerful anti-inflammatory steroid for many conditions.', uses: 'Asthma flares, allergic reactions, autoimmune diseases, inflammation, joint pain.', dosage: 'Varies widely: 5–60 mg/day depending on condition. Taper gradually to stop.', sideEffects: 'Weight gain, mood changes, insomnia, increased appetite, high blood sugar.', warnings: '⚠️ Never stop suddenly (must taper). Long-term use causes bone loss, cataracts, and adrenal issues.', icon: '💊' },
  { name: 'Gabapentin', aliases: ['gabapentin','neurontin','gabapin'], category: 'Nerve Pain', description: 'Anti-seizure medication also used for nerve pain.', uses: 'Nerve pain (neuropathy), epilepsy, postherpetic neuralgia, restless legs, anxiety.', dosage: 'Adults: 300–3600 mg/day in 3 divided doses. Increase gradually.', sideEffects: 'Drowsiness, dizziness, fatigue, swelling, weight gain.', warnings: 'Do not stop suddenly (risk of seizures). Adjust dose for kidney problems.', icon: '⚡' },
  { name: 'Methotrexate', aliases: ['methotrexate','trexall'], category: 'Immunosuppressant', description: 'Immunosuppressant for autoimmune diseases and certain cancers.', uses: 'Rheumatoid arthritis, psoriasis, certain cancers, ectopic pregnancy.', dosage: '⚠️ Usually taken ONCE WEEKLY (not daily!). 7.5–25 mg weekly for autoimmune.', sideEffects: 'Nausea, fatigue, mouth sores, liver toxicity, low blood counts.', warnings: '⚠️ Take folic acid supplement. Regular blood tests essential. Not for pregnant women. WEEKLY dosing!', icon: '⚠️' },
  { name: 'Allopurinol', aliases: ['allopurinol','zyloprim','zyloric'], category: 'Gout', description: 'Reduces uric acid production to prevent gout attacks.', uses: 'Gout prevention, high uric acid, kidney stones (uric acid type).', dosage: 'Adults: 100–300 mg once daily. Start low to avoid triggering gout flare.', sideEffects: 'Rash, nausea, diarrhea. Rarely: severe skin reactions.', warnings: 'Drink plenty of water. May initially worsen gout (start with colchicine cover). Stop if rash develops.', icon: '🦶' },
  { name: 'Sildenafil', aliases: ['sildenafil','viagra','revatio'], category: 'Erectile Dysfunction / PAH', description: 'PDE5 inhibitor for erectile dysfunction and pulmonary arterial hypertension.', uses: 'Erectile dysfunction, pulmonary arterial hypertension (Revatio).', dosage: 'ED: 50 mg about 1 hour before activity. Range 25–100 mg. Max once daily.', sideEffects: 'Headache, flushing, nasal congestion, dizziness, visual changes.', warnings: '⚠️ Do NOT take with nitrates (dangerous blood pressure drop). Seek help for erection lasting >4 hours.', icon: '💊' },
  { name: 'Tamsulosin', aliases: ['tamsulosin','flomax'], category: 'Prostate', description: 'Alpha-blocker that relaxes prostate and bladder muscles.', uses: 'Benign prostatic hyperplasia (BPH), urinary symptoms, kidney stones.', dosage: 'Adults: 0.4 mg once daily, 30 minutes after the same meal each day.', sideEffects: 'Dizziness, runny nose, abnormal ejaculation, headache.', warnings: 'May cause dizziness when standing up. Caution with cataract surgery (floppy iris).', icon: '🚻' },
  { name: 'Finasteride', aliases: ['finasteride','proscar','propecia'], category: 'Prostate / Hair Loss', description: '5-alpha reductase inhibitor for enlarged prostate and hair loss.', uses: 'BPH (5 mg), male pattern hair loss (1 mg).', dosage: 'BPH: 5 mg daily. Hair loss: 1 mg daily. Takes 3–6 months for effect.', sideEffects: 'Decreased libido, erectile dysfunction, reduced ejaculate.', warnings: '⚠️ Women who are/may become pregnant must NOT handle crushed tablets.', icon: '💇' },
];

export const SYMPTOM_DB: SymptomEntry[] = [
  { symptom: 'Headache', aliases: ['headache','head pain','migraine','head hurts','temple pain'], description: 'Pain or discomfort in any part of the head.', possibleCauses: ['Tension headache','Migraine','Dehydration','Sinusitis','Eye strain','High blood pressure','Caffeine withdrawal','Stress'], advice: 'Rest in a quiet, dark room. Stay hydrated. Apply cold or warm compress to forehead. Try OTC pain relievers.', whenToSeeDoctor: 'Sudden severe "thunderclap" headache, headache with fever/stiff neck, after head injury, with vision changes, worst headache of life.', remedies: ['Paracetamol 500–1000 mg','Ibuprofen 200–400 mg','Plenty of water','Rest in dark room','Cold compress'], icon: '🤕' },
  { symptom: 'Fever', aliases: ['fever','high temperature','pyrexia','hot','chills','feeling hot'], description: 'Body temperature above 100.4°F (38°C).', possibleCauses: ['Viral infection (cold, flu)','Bacterial infection','COVID-19','UTI','Ear infection','Medication reaction'], advice: 'Rest, stay hydrated with water and clear fluids. Light clothing. Sponge with lukewarm water. Take fever reducer if uncomfortable.', whenToSeeDoctor: 'Temperature >103°F (39.4°C), persistent >3 days, with severe headache/stiff neck, rash, difficulty breathing, in infants under 3 months.', remedies: ['Paracetamol 500–1000 mg','Ibuprofen 200–400 mg','Plenty of fluids','Lukewarm sponging','Light clothing'], icon: '🌡️' },
  { symptom: 'Cough', aliases: ['cough','coughing','dry cough','wet cough','phlegm','productive cough'], description: 'Reflexive action to clear airways.', possibleCauses: ['Common cold','Flu','Allergies','Asthma','GERD','Bronchitis','Pneumonia','COVID-19','ACE inhibitor side effect'], advice: 'Stay hydrated. Use honey in warm water. Avoid irritants like smoke. Elevate head when sleeping. Use humidifier.', whenToSeeDoctor: 'Persistent >3 weeks, coughing blood, with high fever, difficulty breathing, chest pain, unexplained weight loss.', remedies: ['Honey in warm water','Cough lozenges','Humidifier','Dextromethorphan (dry cough)','Stay hydrated'], icon: '😷' },
  { symptom: 'Stomach Pain', aliases: ['stomach pain','stomach ache','abdominal pain','belly pain','stomach cramps','gastric pain','tummy ache'], description: 'Pain or discomfort in the abdominal area.', possibleCauses: ['Indigestion','Gas/bloating','Gastritis','Food poisoning','IBS','Ulcers','Appendicitis','Constipation','Menstrual cramps'], advice: 'Rest, eat bland foods (BRAT diet), stay hydrated. Avoid spicy, fatty, and acidic foods. Use heating pad on abdomen.', whenToSeeDoctor: 'Severe sudden pain, with fever/vomiting, blood in stool, pain in lower right abdomen, persistent >48 hours, with inability to eat.', remedies: ['Antacids','Omeprazole 20 mg','Heating pad','BRAT diet','Peppermint tea','Simethicone (gas)'], icon: '🤢' },
  { symptom: 'Fatigue', aliases: ['fatigue','tired','exhaustion','tiredness','no energy','lethargy','weakness','sleepy'], description: 'Persistent feeling of tiredness or lack of energy.', possibleCauses: ['Poor sleep','Anemia','Thyroid disorder','Depression','Diabetes','Vitamin D deficiency','B12 deficiency','Stress','Dehydration','Medication side effects'], advice: 'Ensure 7–9 hours of sleep. Eat balanced diet rich in iron and B vitamins. Exercise moderately (30 min/day). Manage stress. Stay hydrated.', whenToSeeDoctor: 'Persistent >2 weeks despite rest, with unexplained weight loss, chest pain, shortness of breath, depression symptoms, new medications.', remedies: ['Regular sleep schedule','Iron-rich foods','Vitamin D supplement','B12 supplement','Regular exercise','Hydration'], icon: '😴' },
  { symptom: 'Nausea', aliases: ['nausea','nauseous','queasy','feel sick','want to vomit','morning sickness'], description: 'Uneasy sensation in the stomach with urge to vomit.', possibleCauses: ['Food poisoning','Gastroenteritis','Pregnancy','Motion sickness','Medications','Migraine','GERD','Anxiety','Appendicitis'], advice: 'Eat small, frequent bland meals. Sip clear fluids slowly. Try ginger tea or ginger candy. Avoid strong smells. Rest in upright position.', whenToSeeDoctor: 'Persistent >48 hours, with severe abdominal pain, blood in vomit, signs of dehydration, possible pregnancy, head injury.', remedies: ['Ginger tea/candy','Ondansetron 4 mg','Domperidone 10 mg','Dry crackers','Small sips of clear fluids','Peppermint'], icon: '🤮' },
  { symptom: 'Dizziness', aliases: ['dizziness','dizzy','lightheaded','vertigo','room spinning','faint','fainting'], description: 'Feeling of unsteadiness, lightheadedness, or spinning.', possibleCauses: ['Dehydration','Low blood pressure','Vertigo (BPPV)','Ear infection','Anemia','Low blood sugar','Medication side effects','Anxiety'], advice: 'Sit or lie down immediately. Move slowly when changing positions. Stay hydrated. Avoid sudden head movements. Focus on a fixed point.', whenToSeeDoctor: 'With chest pain, severe headache, slurred speech, limb weakness/numbness, high fever, hearing loss, persistent episodes.', remedies: ['Sit/lie down safely','Hydrate well','Eat something (low blood sugar)','Meclizine 25 mg (vertigo)','Slow position changes'], icon: '💫' },
  { symptom: 'Back Pain', aliases: ['back pain','backache','lower back pain','upper back pain','spine pain','lumbago'], description: 'Pain in the upper, middle, or lower back.', possibleCauses: ['Muscle strain','Poor posture','Herniated disc','Arthritis','Sciatica','Kidney stones','Osteoporosis','Sedentary lifestyle'], advice: 'Stay gently active (avoid bed rest >1–2 days). Apply heat or ice. Practice good posture. Gentle stretching. OTC pain relief.', whenToSeeDoctor: 'With leg weakness/numbness, bladder/bowel problems, after trauma, with fever, severe constant pain, unexplained weight loss.', remedies: ['Ibuprofen 400 mg','Paracetamol 1000 mg','Heat pack','Gentle stretching','Good posture','Ice pack (acute injury)'], icon: '🔙' },
  { symptom: 'Sore Throat', aliases: ['sore throat','throat pain','throat hurts','pharyngitis','strep throat','tonsillitis'], description: 'Pain, scratchiness, or irritation of the throat.', possibleCauses: ['Viral infection (cold, flu)','Strep throat','Tonsillitis','Allergies','Dry air','Acid reflux','Mono'], advice: 'Gargle warm salt water. Drink warm fluids with honey. Use throat lozenges. Stay hydrated. Rest voice.', whenToSeeDoctor: 'Severe pain/difficulty swallowing, fever >101°F, rash, swollen neck glands, persistent >1 week, difficulty breathing.', remedies: ['Warm salt water gargle','Honey in warm water','Throat lozenges','Paracetamol','Ibuprofen','Stay hydrated'], icon: '🗣️' },
  { symptom: 'Chest Pain', aliases: ['chest pain','chest tightness','chest pressure','heart pain','chest discomfort'], description: 'Pain or discomfort in the chest area.', possibleCauses: ['Heartburn/GERD','Muscle strain','Anxiety/panic attack','Costochondritis','Angina','Heart attack','Pneumonia','Pulmonary embolism'], advice: '⚠️ CHEST PAIN CAN BE SERIOUS. If sudden, severe, with shortness of breath, arm/jaw pain, or sweating → CALL EMERGENCY IMMEDIATELY (911/999/112).', whenToSeeDoctor: '🚨 IMMEDIATELY if: crushing/squeezing chest pain, pain spreading to arm/jaw, shortness of breath, sweating, nausea, or dizziness with chest pain.', remedies: ['🚨 Call emergency services if cardiac symptoms','Antacids (if confirmed heartburn)','Rest (muscle strain)','Deep breathing (anxiety)'], icon: '🫀' },
  { symptom: 'Shortness of Breath', aliases: ['shortness of breath','breathless','cant breathe','difficulty breathing','dyspnea','breathlessness'], description: 'Difficulty breathing or feeling like you can\'t get enough air.', possibleCauses: ['Asthma','Anxiety','COPD','Pneumonia','Heart failure','Allergic reaction','Anemia','COVID-19','Pulmonary embolism'], advice: '⚠️ Can be serious. Sit upright. Pursed lip breathing. Stay calm. Use inhaler if prescribed.', whenToSeeDoctor: '🚨 IMMEDIATELY if: sudden onset, with chest pain, bluish lips/face, severe wheezing, after choking, with swelling of face/throat.', remedies: ['Sit upright','Pursed lip breathing','Rescue inhaler (if prescribed)','Stay calm','Fresh air','🚨 Call emergency if severe'], icon: '🫁' },
  { symptom: 'Joint Pain', aliases: ['joint pain','arthritis','knee pain','hip pain','shoulder pain','joint swelling','stiff joints'], description: 'Pain, aching, or stiffness in one or more joints.', possibleCauses: ['Osteoarthritis','Rheumatoid arthritis','Gout','Injury/strain','Bursitis','Tendinitis','Lupus','Infection'], advice: 'Rest the affected joint. Apply ice (acute) or heat (chronic). Gentle range-of-motion exercises. OTC pain relief.', whenToSeeDoctor: 'Joint is red/warm/swollen, can\'t move joint, pain after injury, with fever, sudden severe pain in big toe (gout).', remedies: ['Ibuprofen 400 mg','Paracetamol 1000 mg','Ice pack (acute)','Heat pad (chronic)','Gentle exercises','Topical diclofenac gel'], icon: '🦵' },
  { symptom: 'Skin Rash', aliases: ['rash','skin rash','itchy skin','hives','eczema','dermatitis','skin irritation'], description: 'Change in skin color, texture, or appearance with or without itching.', possibleCauses: ['Allergic reaction','Eczema','Contact dermatitis','Fungal infection','Drug reaction','Viral infection','Psoriasis','Heat rash'], advice: 'Avoid scratching. Apply cool compress. Use fragrance-free moisturizer. Antihistamine for itching. Identify and avoid triggers.', whenToSeeDoctor: 'With fever, spreading rapidly, blistering, painful, with breathing difficulty, around eyes/mouth, after new medication.', remedies: ['Cetirizine 10 mg (itching)','Hydrocortisone cream 1%','Cool compress','Calamine lotion','Fragrance-free moisturizer'], icon: '🔴' },
  { symptom: 'Constipation', aliases: ['constipation','constipated','hard stool','cant poop','bowel problems','irregular bowels'], description: 'Infrequent bowel movements or difficulty passing stool.', possibleCauses: ['Low fiber diet','Dehydration','Lack of exercise','Medications','IBS','Hypothyroidism','Ignoring urge to go'], advice: 'Increase fiber (fruits, vegetables, whole grains). Drink plenty of water (8+ glasses). Exercise regularly. Don\'t ignore urge to go.', whenToSeeDoctor: 'With blood in stool, severe pain, persistent >3 weeks, unexplained weight loss, sudden change in bowel habits, vomiting.', remedies: ['High-fiber foods','Psyllium husk (Metamucil)','Lactulose syrup','Bisacodyl 5 mg','Plenty of water','Regular exercise'], icon: '🚽' },
  { symptom: 'Diarrhea', aliases: ['diarrhea','diarrhoea','loose stool','watery stool','runs','upset stomach'], description: 'Frequent loose or watery bowel movements.', possibleCauses: ['Food poisoning','Viral gastroenteritis','Bacterial infection','IBS','Lactose intolerance','Medication side effect','Anxiety'], advice: 'Stay hydrated with ORS or clear fluids. Eat bland foods (BRAT diet). Avoid dairy, caffeine, and fatty foods. Rest.', whenToSeeDoctor: 'Blood or black stools, high fever, signs of dehydration, persistent >3 days, severe pain, recent antibiotic use.', remedies: ['ORS (oral rehydration solution)','Loperamide 2–4 mg','BRAT diet','Plenty of fluids','Probiotics','Zinc supplements (children)'], icon: '🚽' },
  { symptom: 'Insomnia', aliases: ['insomnia','cant sleep','sleep problems','sleeplessness','trouble sleeping','waking up at night'], description: 'Difficulty falling asleep, staying asleep, or getting restful sleep.', possibleCauses: ['Stress/anxiety','Poor sleep habits','Depression','Caffeine','Screen time','Pain','Medications','Sleep apnea'], advice: 'Consistent sleep schedule. Dark, cool room. No screens 1 hour before bed. Limit caffeine after noon. Relaxation techniques.', whenToSeeDoctor: 'Persistent >4 weeks, affecting daily function, with daytime sleepiness/snoring (sleep apnea), with depression/anxiety.', remedies: ['Sleep hygiene routine','Melatonin 1–3 mg','Chamomile tea','Limit caffeine','No screens before bed','Relaxation/meditation'], icon: '🌙' },
  { symptom: 'Anxiety', aliases: ['anxiety','anxious','worried','nervousness','panic','panic attack','stressed','racing heart'], description: 'Excessive worry, nervousness, or fear that interferes with daily life.', possibleCauses: ['Generalized anxiety disorder','Panic disorder','Stress','Caffeine','Thyroid disorders','Medications','Trauma/PTSD'], advice: 'Practice deep breathing (4-7-8 technique). Regular exercise. Limit caffeine and alcohol. Mindfulness meditation. Talk to someone you trust.', whenToSeeDoctor: 'Interfering with daily life, panic attacks, with depression, persistent >2 weeks, affecting relationships/work, with physical symptoms.', remedies: ['Deep breathing exercises','Regular exercise','Limit caffeine','Meditation/mindfulness','Chamomile tea','Talk therapy'], icon: '😰' },
  { symptom: 'Allergic Reaction', aliases: ['allergy','allergic','allergic reaction','hay fever','runny nose','sneezing','itchy eyes','allergies'], description: 'Immune system overreaction to normally harmless substances.', possibleCauses: ['Pollen','Dust mites','Pet dander','Food allergies','Insect stings','Medications','Mold','Latex'], advice: 'Identify and avoid triggers. Take antihistamines. Use nasal spray for nasal symptoms. Keep windows closed during high pollen.', whenToSeeDoctor: '🚨 EMERGENCY if: swelling of face/throat, difficulty breathing, rapid pulse, dizziness (anaphylaxis). Otherwise: persistent symptoms, affecting quality of life.', remedies: ['Cetirizine 10 mg','Loratadine 10 mg','Fluticasone nasal spray','Eye drops','Avoid triggers','🚨 EpiPen for anaphylaxis'], icon: '🤧' },
  { symptom: 'Ear Pain', aliases: ['ear pain','earache','ear infection','ear hurts','otitis'], description: 'Pain in or around the ear.', possibleCauses: ['Ear infection (otitis media)','Swimmer\'s ear','Earwax buildup','Sinus infection','Tooth problems','TMJ disorder','Cold/flu'], advice: 'Apply warm compress to ear. OTC pain relief. Keep ear dry. Chewing gum may help equalize pressure.', whenToSeeDoctor: 'With fever, discharge from ear, hearing loss, persistent >2–3 days, in children under 6 months, severe pain.', remedies: ['Paracetamol 500–1000 mg','Ibuprofen 200–400 mg','Warm compress','Ear drops (if prescribed)','Chewing gum (pressure)'], icon: '👂' },
  { symptom: 'Eye Problems', aliases: ['eye pain','blurry vision','red eyes','eye irritation','dry eyes','watery eyes','itchy eyes','conjunctivitis','pink eye'], description: 'Pain, redness, itching, or vision changes in the eyes.', possibleCauses: ['Conjunctivitis (pink eye)','Dry eyes','Allergies','Eye strain','Foreign body','Glaucoma','Stye','Contact lens issues'], advice: 'Rest eyes. Apply warm or cool compress. Use artificial tears. Avoid rubbing eyes. Follow 20-20-20 rule for screen time.', whenToSeeDoctor: '🚨 URGENT: Sudden vision loss, severe pain, chemical exposure, eye injury, flashing lights/floaters, with severe headache.', remedies: ['Artificial tears','Cool compress','Antihistamine eye drops (allergies)','20-20-20 rule','Warm compress (stye)'], icon: '👁️' },
  { symptom: 'Toothache', aliases: ['toothache','tooth pain','dental pain','tooth hurts','teeth hurt'], description: 'Pain in or around a tooth.', possibleCauses: ['Tooth decay/cavity','Gum disease','Cracked tooth','Abscess','Wisdom teeth','Grinding (bruxism)','Sensitive teeth'], advice: 'Rinse with warm salt water. Use OTC pain relief. Apply clove oil to affected area. Floss gently. Avoid very hot/cold foods.', whenToSeeDoctor: 'Severe throbbing pain, swelling of face/jaw, fever, bad taste (abscess), pain lasting >2 days, with ear pain.', remedies: ['Ibuprofen 400 mg','Paracetamol 500–1000 mg','Warm salt water rinse','Clove oil','Sensitive toothpaste','Ice pack on cheek'], icon: '🦷' },
  { symptom: 'Urinary Problems', aliases: ['uti','urinary infection','burning urination','frequent urination','painful urination','blood in urine','bladder'], description: 'Pain, burning, or changes in urination patterns.', possibleCauses: ['Urinary tract infection (UTI)','Kidney stones','Enlarged prostate','Sexually transmitted infection','Overactive bladder','Diabetes'], advice: 'Drink plenty of water. Urinate frequently. Wipe front to back (women). Avoid caffeine and alcohol. Cranberry supplements may help prevent UTIs.', whenToSeeDoctor: 'Blood in urine, fever with UTI symptoms, severe flank pain (kidney stones), inability to urinate, in men (all urinary symptoms).', remedies: ['Plenty of water','Cranberry supplements','Paracetamol (pain)','OTC UTI pain relief (phenazopyridine)','See doctor for antibiotics'], icon: '🚻' },
  { symptom: 'Muscle Pain', aliases: ['muscle pain','sore muscles','myalgia','body aches','muscle cramps','muscle spasm'], description: 'Pain or discomfort in muscles.', possibleCauses: ['Exercise/overuse','Tension/stress','Flu/viral illness','Fibromyalgia','Dehydration','Electrolyte imbalance','Medication side effects','Injury'], advice: 'Rest affected muscles. Apply ice (first 48h) then heat. Gentle stretching. Stay hydrated. Massage.', whenToSeeDoctor: 'With dark urine (rhabdomyolysis), severe weakness, after starting new medication, with swelling/redness, persistent >1 week.', remedies: ['Ibuprofen 400 mg','Paracetamol 1000 mg','Ice then heat','Gentle stretching','Epsom salt bath','Massage','Hydration'], icon: '💪' },
];

// Search function with fuzzy matching
export function searchMedicine(query: string): MedicineEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  
  // Exact alias match first
  const exact = MEDICINE_DB.filter(m => m.aliases.some(a => a === q));
  if (exact.length > 0) return exact;
  
  // Partial match
  const partial = MEDICINE_DB.filter(m => 
    m.aliases.some(a => a.includes(q) || q.includes(a)) ||
    m.name.toLowerCase().includes(q) ||
    m.category.toLowerCase().includes(q) ||
    m.uses.toLowerCase().includes(q)
  );
  if (partial.length > 0) return partial;

  // Word-level match
  const words = q.split(/\s+/);
  return MEDICINE_DB.filter(m => 
    words.some(w => w.length > 2 && (
      m.name.toLowerCase().includes(w) ||
      m.aliases.some(a => a.includes(w)) ||
      m.uses.toLowerCase().includes(w) ||
      m.description.toLowerCase().includes(w)
    ))
  );
}

export function searchSymptom(query: string): SymptomEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  const exact = SYMPTOM_DB.filter(s => s.aliases.some(a => a === q));
  if (exact.length > 0) return exact;

  const partial = SYMPTOM_DB.filter(s =>
    s.aliases.some(a => a.includes(q) || q.includes(a)) ||
    s.symptom.toLowerCase().includes(q) ||
    s.description.toLowerCase().includes(q)
  );
  if (partial.length > 0) return partial;

  const words = q.split(/\s+/);
  return SYMPTOM_DB.filter(s =>
    words.some(w => w.length > 2 && (
      s.symptom.toLowerCase().includes(w) ||
      s.aliases.some(a => a.includes(w)) ||
      s.description.toLowerCase().includes(w) ||
      s.possibleCauses.some(c => c.toLowerCase().includes(w))
    ))
  );
}

// Get medicine categories for browsing
export function getMedicineCategories(): string[] {
  return [...new Set(MEDICINE_DB.map(m => m.category))];
}

export function getMedicinesByCategory(category: string): MedicineEntry[] {
  return MEDICINE_DB.filter(m => m.category === category);
}
